version: '3.1'

services:
  api:
    image: neosign/api:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - TARGET=development
      - ENVIRONMENT=local
      - REDIS_HOST=redis

  redis:
    hostname: redis
    image: redis
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - backend

networks:
  backend:

volumes:
  redis-data:

